# Copy this file to .github/workflows/gds.yaml

name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create and publish the GDS artifact
        uses: TinyTapeout/tt-gds-action/custom_gds@tt05
        with: 
          top_module: tt_um_matt_divider_test
          gds_path: gds/tt_um_matt_divider_test.gds
          lef_path: lef/tt_um_matt_divider_test.lef
          verilog_path: verilog/tt_um_matt_divider_test.v
